### PR TITLE
added pseudo code for meal recipe search

### PR DESCRIPTION
**Pull request by BrienBarr**
created the meal_logic.js file with the pseudo code for the meal recipe search

### CODE REVIEW

**Comment by tussingj89** [comment]
looks good

**Comment by tussingj89** [comment]
looks good

**Comment by BrienBarr** [comment]
Added the functionality of retrieving a meal with the random meal button

**Comment by tussingj89** [comment]
looks good to me

**Review by tussingj89 — APPROVED** [review]
all changes look good to me

**Pull request merged**
